/**
 * How peer sync works:
 *
 * SYncMSG: on a connection both peers send the current VV of each object they have.
 *      Also send the IDS of any state based objects.
 *
 * on a SYncMSG: peer checks objects the other peer has.
 *      ops objects: check diff, send missing ops to other peer
 *      state object: send current state
 *
 * on sync complete ():
 *      clear the message queue.
 *
 */


/**
 *
 * @param legion {Legion}
 * @param objectStore {ObjectStore}
 * @param peerConnection {PeerConnection}
 * @constructor
 */
function PeerSync(legion, objectStore, peerConnection) {
    this.legion = legion;
    this.objectStore = objectStore;
    this.peerConnection = peerConnection;

    /**
     * True when syncing is done.
     * @type {boolean}
     */
    this.isSynced = false;

    /**
     * Contains updates to be sent after sync.
     * TODO: this queue must have some parsing to eliminate duplicates and merge state propagation of the same object?
     * @type {ALQueue}
     */
    this.queueAfterSync = new ALQueue();

    /**
     * A map of all objects the other peer maintains.
     * @type {ALMap}
     */
    this.sharedObjects = new ALMap();

    var ps = this;
    this.psTimeout = setTimeout(function () {
        console.error("No PeerSync in time.", ps.legion.id, ps.peerConnection.remoteID);
    }, 5 * 1000);
}

PeerSync.prototype.finalize = function () {
    this.isSynced = false;
    this.peerConnection = null;
    this.queueAfterSync.clear();
    this.queueAfterSync = null;
    this.sharedObjects.clear();
    this.sharedObjects = null;
    clearTimeout(this.psTimeout);
};

/**
 * Clears the queue, sending all messages to the peer.
 */
PeerSync.prototype.clearQueue = function () {
    if (!this.isSynced) {
        console.error("Clearing queue before sync.");
    } else {
        var pop = this.queueAfterSync.pop();
        if (pop) {
            console.log("Clearing queue to: " + this.peerConnection.remoteID + ". Size of queue: " + (this.queueAfterSync.size() + 1));
        }
        while (typeof pop != "undefined") {
            this.peerConnection.send(pop);
            pop = this.queueAfterSync.pop();
        }
    }
};

/**
 * Receives from remote peer a message generated by PeerSync.handleSync.
 * @param message {...{content: {states: [], missing_ops: []}}}
 */
PeerSync.prototype.handleSyncAnswer = function (message) {
    var states = message.content.states;
    var operations = message.content.missing_ops;

    for (var j = 0; j < states.length; j++) {
        var my_state_crdt = this.objectStore.crdts.get(states[j].id);
        if (!my_state_crdt) {
            console.warn("I should not be here.");
        } else {
            my_state_crdt.stateFromNetwork(my_state_crdt.fromJSONString(states[j].state), this.peerConnection);
        }
    }
    for (var i = 0; i < operations.length; i++) {
        var my_op_crdt = this.objectStore.crdts.get(operations[i].id);
        if (!my_op_crdt) {
            console.warn("I should not be here.");
        } else {
            my_op_crdt.operationsFromNetwork(operations[i].operations, this.peerConnection);
        }
    }

    this.isSynced = true;
    this.clearQueue();
};

/**
 * Receives from remote peer a message generated by PeerSync.sync.
 * @param message {...{content: {stateObjects: [], operationObjects: []}}}
 */
PeerSync.prototype.handleSync = function (message) {
    var stateObjects = message.content.stateObjects;
    var operationObjects = message.content.operationObjects;

    var answer = {missing_ops: [], states: []};
    for (var i = 0; i < operationObjects.length; i++) {
        var my_op_crdt = this.objectStore.crdts.get(operationObjects[i].id);
        if (!my_op_crdt)
            continue;
        var my_crdts_vv = my_op_crdt.getVersionVector();
        var vvDiff = this.objectStore.versionVectorDiff(my_crdts_vv, operationObjects[i].vv);
        if (Object.keys(vvDiff.vv2.missing).length > 0) {
            answer.missing_ops.push({
                id: my_op_crdt.objectID,
                operations: my_op_crdt.getOperations(vvDiff.vv2.missing)
            });
        }
    }
    for (var j = 0; j < stateObjects.length; j++) {
        var my_state_crdt = this.objectStore.crdts.get(stateObjects[j].id);
        if (!my_state_crdt)
            continue;
        answer.states.push({id: my_state_crdt.objectID, state: my_state_crdt.toJSONString(my_state_crdt.getState())});
    }

    var ps = this;
    this.legion.generateMessage(this.objectStore.handlers.peerSyncAnswer.type, answer, function (result) {
        result.destination = ps.peerConnection.remoteID;
        ps.peerConnection.send(result);
    });
};

PeerSync.prototype.sync = function () {
    var ps = this;
    var messageContent = {stateObjects: [], operationObjects: []};

    var localKeys = this.objectStore.crdts.keys();
    for (var i = 0; i < localKeys.length; i++) {
        var crdt = this.objectStore.crdts.get(localKeys[i]);
        if (crdt.crdt.propagation == CRDT.STATE_BASED) {
            messageContent.stateObjects.push({id: crdt.objectID});
        } else if (crdt.crdt.propagation == CRDT.OP_BASED) {
            messageContent.operationObjects.push({id: crdt.objectID, vv: crdt.getVersionVector()});
        } else {
            console.error("Shit happened.")
        }
    }
    this.legion.generateMessage(this.objectStore.handlers.peerSync.type, messageContent, function (result) {
        result.destination = ps.peerConnection.remoteID;
        ps.legion.messagingAPI.broadcastMessage(result);
    });
};

var CRDT_LIB = {};

/**
 *
 * @param legion {Legion}
 * @constructor
 */
function ObjectStore(legion) {
    this.legion = legion;

    this.types = new ALMap();
    this.crdts = new ALMap();

    this.peerSyncs = new ALMap();

    var os = this;
    this.handlers = {
        peerSync: {
            type: "OS:PS", callback: function (message) {
                console.info(message);
                var ps = os.peerSyncs.get(message.sender);
                if (!ps) {
                    console.warn("Got OS:PS for unknown peer.");
                } else {
                    clearTimeout(ps.psTimeout);
                    ps.handleSync(message);
                }
            }
        },
        peerSyncAnswer: {
            type: "OS:PSA", callback: function (message) {
                console.info(message);
                var ps = os.peerSyncs.get(message.sender);
                if (!ps) {
                    console.warn("Got OS:PSA for unknown peer.");
                } else {
                    ps.handleSyncAnswer(message);
                }
            }
        },
        state_propagation: {
            type: "OS:SP", callback: function () {
                console.error("Not Implemented: state_propagation");
                //TODO: state_propagation
            }
        },
        operations_propagation: {
            type: "OS:OP", callback: function () {
                console.error("Not Implemented: operations_propagation");
                //TODO: operations_propagation
            }
        },
        version_vector_propagation: {
            type: "OS:VVP", callback: function () {
                console.error("Not Implemented: version_vector_propagation");
                //TODO: version_vector_propagation
            }
        }
    };


    /**
     * TODO: this queue must have some parsing to eliminate duplicates and merge state propagation of the same object?
     * TODO: the timer
     * @type {ALQueue}
     */
    this.serverQueue = new ALQueue();

    /**
     * TODO: this queue must have some parsing to eliminate duplicates and merge state propagation of the same object?
     * TODO: the timer
     * @type {ALQueue}
     */
    this.peersQueue = new ALQueue();


    var peers = this.legion.overlay.getPeers();
    if (peers.length > 0) {
        console.warn("Already have peers!", peers.length);
    }
    for (var i = 0; i < peers.length; i++) {
        var p = new PeerSync(this.legion, this, peers[i]);
        this.peerSyncs.set(peers[i].remoteID, p);
        p.sync();
    }


    this.legion.messagingAPI.setHandlerFor(this.handlers.peerSync.type, this.handlers.peerSync.callback);
    this.legion.messagingAPI.setHandlerFor(this.handlers.peerSyncAnswer.type, this.handlers.peerSyncAnswer.callback);
    this.legion.messagingAPI.setHandlerFor(this.handlers.state_propagation.type, this.handlers.state_propagation.callback);
    this.legion.messagingAPI.setHandlerFor(this.handlers.operations_propagation.type, this.handlers.operations_propagation.callback);
    this.legion.messagingAPI.setHandlerFor(this.handlers.version_vector_propagation.type, this.handlers.version_vector_propagation.callback);

}

/**
 * Defines a CRDT that can later be instantiated.
 * @param crdt {crtd_type}
 */
ObjectStore.prototype.defineCRDT = function (crdt) {
    if (this.types.contains(crdt.type)) {
        console.error("Can't redefine existing CRDT.", crdt);
    } else {
        this.types.set(crdt.type, crdt);
    }
};

/**
 * Creates or obtains a CRDT.
 * @param objectID
 * @param type
 * @returns {Object}
 */
ObjectStore.prototype.get = function (objectID, type) {
    if (!this.types.contains(type)) {
        console.error("No typedef found for CRDT.", type);
    } else {
        if (this.crdts.contains(objectID)) {
            return this.crdts.get(objectID);
        } else {
            var crdt = this.types.get(type);
            var instance = new CRDT(objectID, crdt, this);
            this.crdts.set(objectID, instance);
            return instance;
        }
    }
};

/**
 *
 * @param clientID {number}
 * @param operationID {number}
 */
ObjectStore.prototype.propagate = function (clientID, operationID) {
    console.warn("Not implemented: propagate", clientID, operationID);
};

ObjectStore.prototype.propagateAll = function (ops) {
    if (options.except) {
        //Send to all but c;
    } else {

    }
    console.warn("Not implemented: propagateALL", ops);
};

/**
 * Overlay added signalling connection.
 * @param serverConnection
 */
ObjectStore.prototype.onServerDisconnection = function (serverConnection) {
    console.warn("Not Implemented: onServerDisconnection");
    //TODO: objectsStore in charge of adding objects to objects server.
};

/**
 * Signalling connection dropped.
 * @param serverConnection
 */
ObjectStore.prototype.onServerConnection = function (serverConnection) {
    console.warn("Not Implemented: ObjectStore.onServerConnection");
    //TODO: objectsStore NO LONGER in charge of adding objects to objects server.
};

/**
 * Overlay added a peer.
 * @param peerConnection
 */
ObjectStore.prototype.onClientConnection = function (peerConnection) {
    var p = new PeerSync(this.legion, this, peerConnection);
    this.peerSyncs.set(peerConnection.remoteID, p);
    p.sync();
};

/**
 * A peer dropped the connection.
 * @param peerConnection
 */
ObjectStore.prototype.onClientDisconnection = function (peerConnection) {
    var p = this.peerSyncs.get(peerConnection.remoteID);
    this.peerSyncs.delete(peerConnection.remoteID);
    p.finalize();
};

/**
 * Returns the operations missing at each in form: {vv1:{missing:[]}, vv2:{missing:[]}}.
 * @param vv1
 * @param vv2
 * @returns {{vv1: {missing: {}}, vv2: {missing: {}}}}
 */
ObjectStore.prototype.versionVectorDiff = function (vv1, vv2) {
    var ret = {vv1: {missing: {}}, vv2: {missing: {}}};
    var keys1 = Object.keys(vv1);
    var keys2 = Object.keys(vv2);
    for (var i = 0; i < keys1.length; i++) {
        var currentKey = keys1[i];
        if (!vv2[currentKey]) {
            ret.vv2.missing[currentKey] = [];
            for (var op_i = 1; op_i <= vv1[currentKey]; op_i++) {
                ret.vv2.missing[currentKey].push(op_i);
            }
        } else if (vv2[currentKey] > vv1[currentKey]) {
            ret.vv1.missing[currentKey] = [];
            for (var op_i = vv1[currentKey] + 1; op_i <= vv2[currentKey]; op_i++) {
                ret.vv1.missing[currentKey].push(op_i);
            }
        }
    }

    for (var j = 0; j < keys2.length; j++) {
        var currentKey = keys2[i];
        if (!vv1[currentKey]) {
            ret.vv1.missing[currentKey] = [];
            for (var op_i = 1; op_i <= vv2[currentKey]; op_i++) {
                ret.vv1.missing[currentKey].push(op_i);
            }
        } else if (vv1[currentKey] > vv2[currentKey]) {
            ret.vv2.missing[currentKey] = [];
            for (var op_i = vv2[currentKey] + 1; op_i <= vv1[currentKey]; op_i++) {
                ret.vv2.missing[currentKey].push(op_i);
            }
        }
    }

    console.info(ret);
    return ret;
};

/**
 *
 * @param objectID {String}
 * @param options {{onlyTo}|{except}|{all}}
 */
ObjectStore.prototype.propagateState = function (objectID, options) {
    console.warn("Not implemented: propagateState", objectID, options);
    if (options.onlyTo) {
        //Send to c;
    } else if (options.except) {
        //Send to all but c;
    } else if (options.all) {
        //Send to all;
    }
};